# DataFusion Fuzzer Configuration

# Random seed for reproducibility
seed = 42

# Number of fuzzing rounds to run
rounds = 3

# Number of queries to generate per round
queries_per_round = 10

# Query timeout in seconds
timeout_seconds = 30

# Path to log directory
log_path = "logs"

# Display logs to stdout as well as log files
display_logs = false

# Enable TUI display
enable_tui = true

# Sample interval for query display (seconds)
sample_interval_secs = 5

# Table generation parameters
max_column_count = 5
max_row_count = 100
max_expr_level = 3
max_table_count = 3
